<div class="jumbotron">


    <h1>Demographics</h1>
    <p class="lead">Please choose your sex:</p>
    <div style="width:70px; margin:0 auto;">
        <label class="radio">
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
            Male</label>
        <label class="radio">
            <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
            Female</label>
    </div>

    <p>&nbsp;</p>
    <p><strong>Please read the following before clicking 'Next':</strong></p>
    <p>On the next page you will view a 45 second video.</p>
    <p><strong>Please note:</strong> The video will <strong>auto-play</strong>, and it will only place <strong>once</strong> before automatically moving to the next page.</p>
    <p>You will not be able to pause the video and volume is not necessary.</p>
    <p>&nbsp;</p>
    <p><button class="btn btn-primary" type="button" href="#">Next</button></p>
</div>