<div class="jumbotron">
    <div class="suspect">
        <ul class="thumbnails">
            <li class="span3">
                <div class="thumbnail">
                    <img src="Line-Up/Suspect1Seq.jpg">
                    <label class="lineup">
                        <input type="radio" name="optionsRadios" id="optionsRadios1" value="yes">
                        Yes
                    </label>
                    <label class="lineup">
                        <input type="radio" name="optionsRadios" id="optionsRadios2" value="no">
                        No
                    </label>

                </div>
            </li>
        </ul>

        <p><button class="btn btn-primary" type="button" href="#">Next</button></p>
    </div>
</div>