<div class="jumbotron">
    <h1>Suspect Line-up</h1>
    <p class="lead">You will now take part in the eyewitness identification task. The perpetrator within the previously viewed video MAY or MAY NOT be within the line-up.</p>
    <div style="width:450px; margin:0 auto;">
        <p><strong>It is important you read the following before clicking 'Next':</strong> </p>
        <ul style="text-align:left">
            <li>You can take as much time as you'd like.      </li>
            <li>You will view all 6 suspects at the same time.</li>
            <li>You can only choose 1 suspect as the perpetrator.</li>
            <li>If you cannot identify the perpetrator within the line-up, select the 'Perpetrator not present' option.</li>
        </ul>
        <p><button class="btn btn-primary" type="button" href="#">Next</button></p>
    </div>
</div>