<div class="jumbotron">
    <ul class="thumbnails">
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
        <li class="span3">
            <div class="thumbnail">
                <img src="Line-Up/Suspect1Seq.jpg">
            </div>
        </li>
    </ul> 
    <p class="lead">OR<br></p>
    <label class="suspect" style="text-align:center"><p class="lead"> 
            <input type="radio" name="optionsRadios" id="optionsRadios1" value="yes"> perpetrator not present </p>
    </label> 

    <p><button class="btn btn-primary" type="button" href="#">Next</button></p>
</div>