<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Bear Witness')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/main.css')
                ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                ->prependStylesheet('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css');
        ?>

        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

    </head>
    <body>
        <div class="container">
            <div class="masthead">
                <h3 class="muted">YouWitness.com.au</h3>
            </div>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li class="active"> <a href="#"> Step 1 <small>Consent</small> </a> </li>
                            <li> <a href="#"> Step 2 <small>Demographics</small> </a> </li>
                            <li> <a href="#"> Step 3 <small>Watch Video</small> </a> </li>
                            <li> <a href="#"> Step 4 <small>Word Search</small> </a> </li>
                            <li> <a href="#"> Step 5 <small>Suspect Line-up</small> </a> </li>
                            <li> <a href="#"> Step 6 <small>Evaluation</small> </a> </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Jumbotron -->
            <div class="jumbotron">
                <h1>YouWitness </h1>
                <p class="lead">YouWitness is an online eyewitness identification experiment. The purpose is to examine  line-up circumstances for accurate eyewitness identification. The  test will take no longer than 5-10 minutes. Before continuing, please read the <a href="#below">information below</a>.</p>
                <p>By clicking the 'I Accept' button, you are consenting to the conditions listed below. Any concerns or questions please email researcher <a href="mailto:asbisa@deakin.edu.au">Alyssa Sbisa.</a></p>
                <p><a class="btn btn-large btn-primary" href="#">I Accept</a></p>
            </div>
            <hr>
            <div class="row-fluid" id="below">
                <div class="span4">
                    <h4>Conditions</h4>
                    <p>It is required that you are over 18 years of age and can sufficiently read English.</p>
                    <p>The test should take no longer than 5-10 minutes, however you are permitted to take as much time as you like. <br>
                        <br>
                        You have the right to withdraw from further participation at any stage along the test, however the data you have entered will not be recorded or analysed.</p>
                    <p>There are no risks associated with this research, and your answers will be anonymous and confidential. <br>
                        <br>
                        At the conclusion of the test, you'll be provided with the option to enter your email address to be informed of the research results when they are released in October 2013. Alternatively, you can <a href="results.html">click here</a> to submit your interest.</p>
                </div>
                <div class="span4">
                    <h4>Procedure</h4>
                    <ul>
                        <li>Nominate your sex: male or female</li>
                        <li>View  a 45 second video</li>
                        <li>Play a timed (60 second) word puzzle</li>
                        <li>View a suspect line-up</li>
                        <li>Rate your level of confidence in your selection</li>
                    </ul>
                </div>
                <div class="span4">
                    <h4>Complaints</h4>
                    <p>If you have complaints about any aspect of the project, the way it is being conducted or any questions about your rights as a research participant, then you may contact:</p>
                    <address>
                        <strong>The Manager,<br>
                            Research Integrity,<br>
                            Deakin University</strong><br>
                        221 Burwood Highway<br>
                        Burwood Victoria 3125<br>
                        <abbr title="Phone">P:</abbr> +61 9251 7129
                    </address>
                    <p><a href="mailto:research-ethics@deakin.edu.au">research-ethics@deakin.edu.au</a></p>
                </div>
            </div>
            <div class="footer">
                <p class="copy">&copy; YouWitness.com.au 2013</p>
            </div>
        </div>
</html>
