<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('YouWitness')->setAutoEscape(false); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>
        <?php
        //get current view model
        $children = $this->viewModel()->getCurrent()->getChildren();
        $child = $children[0];

        if (SERVER_TYPE == 'development') {
            echo $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/main.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css');

            echo $this->headScript()
                    ->appendFile('/js/config.dev.js', 'text/javascript')
                    ->appendFile('/js/dojo/dojo/dojo.js', 'text/javascript')
                    ->appendFile($child->app_script, 'text/javascript');
        } elseif (SERVER_TYPE == 'test') {
            echo $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/main.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css');

            echo $this->headScript()
                    ->appendFile('/js/config.dev.js', 'text/javascript')
                    ->appendFile('/js/dojo/dojo/dojo.js', 'text/javascript')
                    ->appendFile($child->app_script, 'text/javascript');
        } else {
            echo $this->headLink()
                    ->prependStylesheet('https://s3-ap-southeast-2.amazonaws.com/youwitness/css/main.min.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css')
                    ->prependStylesheet('http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css');

            echo $this->headScript()
                    ->appendFile('/js/config.js', 'text/javascript')
                    ->appendFile('https://s3-ap-southeast-2.amazonaws.com/youwitness/js/dojo.js', 'text/javascript')
                    ->appendFile($child->app_script, 'text/javascript');
        }
        ?>
        <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-41225808-1', 'youwitness.com.au');
            ga('send', 'pageview');

        </script>
    </head>
    <body>
        <div class="container">
            <div class="masthead">
                <h3 class="muted">YouWitness.com.au</h3>
            </div>
            <div id="nav"></div>
            <div id="content">
                <?php echo $this->content; ?>
            </div>
            <div class="footer">
                <p class="copy">&copy; YouWitness.com.au 2013</p>
            </div>
        </div>
    </body>
</html>
